SAAP-69 Adding AWS Cloud Provider requirements
stakater-archive/StakaterCloudDocs-Archived pull request #137
Opened 2021-06-28 12:15 UTC by TehreemNisa

SAAP-69 Adding AWS Cloud Provider requirements

2021-06-28 12:17 UTC, stakater-user commented
@TehreemNisa Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/89f7c8d5d52d07a983e4b2af184590d05a53499c/checks) has Failed!

2021-06-28 17:33 UTC, usamaahmadkhan requested changes

2021-06-28 17:33 UTC, usamaahmadkhan commented on content/sre/cloud-provider/aws.md
> +An AWS subscription is needed to create and manage cluster on azure. The following criteria must be met
AWS Account not subscription. Azure has subscription. Plz change throughout the document.

2021-06-28 17:33 UTC, usamaahmadkhan commented on content/sre/cloud-provider/aws.md
> +  | Virtual Machines | The limit should be 12 i.e of 3 worker + 3 master |
`Varies. The limit should be 12 initially. (Initial deployemnt is 3 master + 3 infra + 3 worker)`

2021-06-29 04:58 UTC, TehreemNisa commented on content/sre/cloud-provider/aws.md
> +An AWS subscription is needed to create and manage cluster on azure. The following criteria must be met
done

2021-06-29 04:58 UTC, TehreemNisa commented on content/sre/cloud-provider/aws.md
> +  | Virtual Machines | The limit should be 12 i.e of 3 worker + 3 master |
done

2021-06-29 05:00 UTC, stakater-user commented
@TehreemNisa Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/f75459cd20156eacffa8d7f22d9e0d7a8020b09a/checks) has Failed!

2021-06-29 10:34 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-137-99837208`

2021-06-30 07:20 UTC, usamaahmadkhan approved these changes

2021-06-30 07:20 UTC, merged

2021-06-30 07:24 UTC, stakater-user commented
@usamaahmadkhan Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.83`