Azure cloud provider SAAP-198
stakater-archive/StakaterCloudDocs-Archived pull request #138
Opened 2021-06-29 11:09 UTC by TehreemNisa

Updating Azure cloud provider docs

2021-06-29 11:14 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-138-8ec2ecca`

2021-06-30 07:24 UTC, usamaahmadkhan requested changes

2021-06-30 07:24 UTC, usamaahmadkhan commented on content/sre/cloud-provider/azure.md
> +  | Machine Specifications | 6 machines of 8x32x120G |
Add this here as well:

`| Region | Region will be identified by the customer |`

2021-06-30 07:44 UTC, TehreemNisa commented on content/sre/cloud-provider/azure.md
> +  | Machine Specifications | 6 machines of 8x32x120G |
done

2021-06-30 07:47 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-138-2a4d3ab2`

2021-06-30 09:02 UTC, usamaahmadkhan approved these changes

2021-06-30 09:03 UTC, merged

2021-06-30 09:07 UTC, stakater-user commented
@usamaahmadkhan Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.84`