add introduction for SKS
stakater-archive/StakaterCloudDocs-Archived pull request #16
Opened 2020-06-19 17:33 UTC by rasheedamir

2020-06-19 17:37 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-1`

2020-06-19 20:17 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-2`

2020-06-24 16:39 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-3`

2020-06-24 16:56 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-4`

2020-06-24 19:34 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-5`

2020-06-24 19:37 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-6`

2020-06-24 19:37 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-7`

2020-06-24 19:42 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-8`

2020-06-24 19:48 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-10`

2020-06-24 19:48 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-12`

2020-06-24 19:48 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-11`

2020-06-24 19:48 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-9`

2020-06-24 19:52 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-13`

2020-06-24 19:52 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-14`

2020-06-24 20:00 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-15`

2020-06-24 20:09 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-16`

2020-06-24 20:16 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-17`

2020-06-24 20:16 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-18`

2020-06-24 20:17 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-19`

2020-06-24 20:17 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-20`

2020-06-24 20:19 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-22`

2020-06-24 20:19 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-21`

2020-06-25 07:28 UTC, kahootali commented on content/sre/introduction/images/README.md
> +
why we need this file?

2020-06-25 08:55 UTC, kahootali commented on .vuepress/config.js
> +            },            {
fix indentation for better readability

2020-06-25 09:54 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-23`

2020-06-25 09:54 UTC, rasheedamir commented
@kahootali fixed

2020-06-25 09:54 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-24`

2020-06-25 09:56 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-25`

2020-06-25 11:57 UTC, usamaahmadkhan requested changes

2020-06-25 11:57 UTC, usamaahmadkhan commented on content/sre/introduction/why-sro.md
> +- Flexible consumption based pricing >Optimize costs with ﬂexible pay-as-you-go pricing model (monthly binding)
space after `>`

2020-06-25 12:00 UTC, usamaahmadkhan approved these changes

2020-06-25 12:04 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/stakaterclouddocs:SNAPSHOT-PR-16-26`

2020-06-25 12:05 UTC, merged