SAAP SRE Authorization draft with saap-customer-cluster-admin role
stakater-archive/StakaterCloudDocs-Archived pull request #171
Opened 2021-08-05 09:18 UTC by TehreemNisa

SAAP SRE Authorization draft with saap-customer-cluster-admin role

2021-08-05 09:31 UTC, rasheedamir commented on content/sre/authentication-authorization/sre-authorization-roles-saap.md
> +## saap-sre-cluster-admin:
why put word sre in here?

2021-08-05 09:31 UTC, rasheedamir commented on content/sre/authentication-authorization/sre-authorization-roles-saap.md
> +# SRE Authorization Roles for SAAP
why put sre?

2021-08-05 11:55 UTC, TehreemNisa commented on content/sre/authentication-authorization/sre-authorization-roles-saap.md
> +# SRE Authorization Roles for SAAP
removed and updated

2021-08-05 11:55 UTC, TehreemNisa commented on content/sre/authentication-authorization/sre-authorization-roles-saap.md
> +## saap-sre-cluster-admin:
removed and updated

2021-08-05 12:01 UTC, stakater-user commented
@TehreemNisa Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/316e25bcb1698a7bc59a0f5b0df4b0a2b4c18d30/checks) has Failed!

2021-08-05 12:01 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-e654169b`

2021-08-05 12:31 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-1a53a61c`

2021-08-05 12:33 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-340a1d72`

2021-08-05 12:44 UTC, rasheedamir commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +## 1. saap-customer-cluster-admin:
Shouldn't we add sentence here?

2021-08-05 12:45 UTC, rasheedamir commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +### Networking
which namespaces? can project admin do samething?

2021-08-05 12:45 UTC, rasheedamir commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +# Authorization Roles for SAAP
mixed usage of word customer and user; we should be using one of them

2021-08-05 12:48 UTC, rasheedamir commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +- Are able to view information about specific nodes and PVs in the cluster, including schequotas and limits on the cluster
schequotas?

2021-08-06 06:00 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-4c075ebb`

2021-08-06 08:02 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-d969f92f`

2021-08-09 06:09 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-4e1b244f`

2021-08-09 06:53 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +- Are able to view information about specific nodes and PVs in the cluster, including schequotas and limits on the cluster
updated

2021-08-09 07:03 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-037add2d`

2021-08-09 07:04 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-d5236d4c`

2021-08-09 09:58 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-11e4da70`

2021-08-09 10:05 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-4be88abb`

2021-08-09 10:11 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +### Networking
updated

2021-08-09 10:14 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-5b3afb37`

2021-08-09 10:23 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-8fd19048`

2021-08-09 10:39 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +# Authorization Roles for SAAP
updated

2021-08-09 12:40 UTC, usamaahmadkhan requested changes

2021-08-09 12:40 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +## 1. saap-cluster-admin:
1. SAAP Cluster Admin (SCA)

2021-08-09 12:40 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +- Customer can view OperatorHub in console
Don't use the word customer in every Item.
Write like this:
SAAP Cluster Admin (SCA) can:
- view alpha
- delete beta
- create/update gamma etc.

2021-08-09 15:02 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-93f847f2`

2021-08-09 15:08 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +- Customer can view OperatorHub in console
updated

2021-08-09 15:09 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +## 1. saap-cluster-admin:
updated

2021-08-09 15:14 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-7eaadaad`

2021-08-09 15:20 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-9cd2328a`

2021-08-09 15:21 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-80e719ca`

2021-08-10 08:00 UTC, usamaahmadkhan requested changes

2021-08-10 08:00 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/curated-list-operators.md
> +SAAP customer cluster admins cannot install any operator from Operator Hub, allowed operators to install are maintained as a curated list by SAAP. This restriction is added as the Operator Lifecycle
`SAAP cluster admins` instead of `SAAP customer cluster admins`

2021-08-10 08:00 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/curated-list-operators.md
> +# Curated List of Operators for Customer Roles
* Curated List of Operators for SAAP clusters

2021-08-10 08:00 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/curated-list-operators.md
> +If the customer requires to install an operator that is not mentioned in the above list , the user can raise a request with Stakater Support.The Stakater team will review and add it to the allowed li
* If the user requires to install an operator that is not mentioned in the above list , the user can raise a request with Stakater Support. The support team will review and add it to the allowed list

2021-08-10 08:00 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +Depending on responsibilities of a role, specific roles can be assigned to customer groups, which enable them to achieve there daily tasks.Below is a list of roles provided by SAAP for different cust
Depending on responsibilities of a role, specific roles can be assigned to user groups, which enable them to achieve there daily tasks. Below is a list of roles provided by SAAP for different user groups

2021-08-10 08:00 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +- Customer can create/verify tokens and access
*user

2021-08-10 08:00 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +- access the reserved ‘saap-customer-admin’ project on the cluster, which allows for the creation of ServiceAccounts with elevated privileges and gives the ability to update default limits and quotas
Do we have this project? What is it used for?

2021-08-10 08:00 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +Only the mentioned permissions above are present for the role, for any other permission required the customer need to raise a case with Stakater Support team.
*user

2021-08-10 08:00 UTC, usamaahmadkhan commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +If customer requires a user to be given saap-cluster-admin role , they can raise a request with Stakater team. Stakater team will add the user to the group and inform customer.
If any user needs to be given saap-cluster-admin role , they can raise a request with Stakater team to assign the desired role to that user .

2021-08-10 08:17 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +- access the reserved ‘saap-customer-admin’ project on the cluster, which allows for the creation of ServiceAccounts with elevated privileges and gives the ability to update default limits and quotas
yes this project is present it is created with this role to give elevated privileges for service accounts and can create limits and quotas for those projects on cluster.

2021-08-10 08:17 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +If customer requires a user to be given saap-cluster-admin role , they can raise a request with Stakater team. Stakater team will add the user to the group and inform customer.
updated

2021-08-10 08:20 UTC, TehreemNisa commented on content/sre/authentication-authorization/curated-list-operators.md
> +SAAP customer cluster admins cannot install any operator from Operator Hub, allowed operators to install are maintained as a curated list by SAAP. This restriction is added as the Operator Lifecycle
Updated

2021-08-10 08:21 UTC, TehreemNisa commented on content/sre/authentication-authorization/curated-list-operators.md
> +# Curated List of Operators for Customer Roles
Updated

2021-08-10 08:21 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +Depending on responsibilities of a role, specific roles can be assigned to customer groups, which enable them to achieve there daily tasks.Below is a list of roles provided by SAAP for different cust
Updated

2021-08-10 08:21 UTC, TehreemNisa commented on content/sre/authentication-authorization/curated-list-operators.md
> +If the customer requires to install an operator that is not mentioned in the above list , the user can raise a request with Stakater Support.The Stakater team will review and add it to the allowed li
Updated

2021-08-10 08:21 UTC, TehreemNisa commented on content/sre/authentication-authorization/saap-authorization-roles.md
> +Only the mentioned permissions above are present for the role, for any other permission required the customer need to raise a case with Stakater Support team.
Updated

2021-08-10 08:22 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-5c5e9e5a`

2021-08-10 08:24 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-171-fb2081a9`

2021-08-10 08:59 UTC, usamaahmadkhan approved these changes

2021-08-10 08:59 UTC, merged

2021-08-10 09:03 UTC, stakater-user commented
@usamaahmadkhan Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.117`