create sq intro
stakater-archive/StakaterCloudDocs-Archived pull request #175
Opened 2021-08-06 19:58 UTC by rasheedamir

2021-08-06 20:02 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-2bcd7ae3`

2021-08-06 20:02 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-d9b6c71e`

2021-08-06 21:47 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-b317de31`

2021-08-07 07:59 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-3725c20d`

2021-08-07 12:54 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-82ba7704`

2021-08-07 13:04 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-3cd98143`

2021-08-09 06:08 UTC, usamaahmadkhan requested changes

2021-08-09 06:08 UTC, usamaahmadkhan commented on content/sre/argocd/01-introduction.md
> +[Argo CD](https://argoproj.github.io/argo-cd/){: target=_blank} is a declarative, GitOps continuous delivery tool for Kubernetes. The deployment environment is a namespace in a container platform.
{: target=_blank} doesn't do anything

2021-08-09 06:08 UTC, usamaahmadkhan commented on content/sre/code-quality/01-introduction.md
> +We SonarQube to analyze your code's quality
* We use Sonarqube

2021-08-09 06:08 UTC, usamaahmadkhan commented on content/sre/code-quality/01-introduction.md
> +**From a business standpoint**, SonarQube offers a strong ROI because its acquisition and setup costs are low, and its intuitive interfaces mean that very little training is required. Add to that the
We are offering it as a managed add-on, should we talk about costs?

2021-08-09 08:06 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-7c152531`

2021-08-09 08:07 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-4aec1b3f`

2021-08-09 08:12 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-175-1c343eae`

2021-08-09 15:04 UTC, usamaahmadkhan approved these changes

2021-08-09 15:04 UTC, merged

2021-08-09 15:09 UTC, stakater-user commented
@usamaahmadkhan Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.116`