SAAP-279 Add additional patterns for Java spring in docs
stakater-archive/StakaterCloudDocs-Archived pull request #216
Opened 2021-09-01 11:12 UTC by TehreemNisa

Add additional patterns for Java spring in docs

2021-09-01 11:16 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-36c27efd`

2021-09-01 11:30 UTC, usamaahmadkhan requested changes

2021-09-01 11:30 UTC, usamaahmadkhan commented on content/sre/logging/logging.md
> +If the customer wants to parse logs themselves for example application log alerting like shown below
don't use word `customer`.


We need to provide them full steps where to add what so they can configure this properly

2021-09-02 05:51 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-1566f0c1`

2021-09-02 06:01 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-0b4ac2d1`

2021-09-02 06:34 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-3bef25ad`

2021-09-02 06:37 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-2abfc249`

2021-09-02 06:38 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-eabf8f9b`

2021-09-02 06:41 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-6e3381cd`

2021-09-02 06:42 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-42a407cf`

2021-09-02 06:51 UTC, usamaahmadkhan requested changes

2021-09-02 06:51 UTC, usamaahmadkhan commented on content/sre/logging/logging.md
> +Parsing application logs which are not in `JSON format` can be done using the below scenario.
*can be done as follows:

2021-09-02 06:51 UTC, usamaahmadkhan commented on content/sre/logging/logging.md
> +## Additional config for non JSON log formats
We should make two sections:
 Parse JSON logs
 (above one)
*Parse non JSON logs
 (this one)

2021-09-02 06:55 UTC, usamaahmadkhan requested changes

2021-09-02 06:55 UTC, usamaahmadkhan commented on content/sre/alerting/log-alerts.md
> +> Note : Additionally you can parse your application logs if they are not in JSON format as specified in this [logging scenario](https://docs.cloud.stakater.com/content/sre/logging/logging.html)
*If you use a customized format for logs in your application, you can describe your own regex to parse logs. See example in our log parsing section

2021-09-02 07:06 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-216-d49f3df5`

2021-09-03 05:34 UTC, TehreemNisa commented on content/sre/alerting/log-alerts.md
> +> Note : Additionally you can parse your application logs if they are not in JSON format as specified in this [logging scenario](https://docs.cloud.stakater.com/content/sre/logging/logging.html)
resolved

2021-09-03 05:34 UTC, TehreemNisa commented on content/sre/logging/logging.md
> +## Additional config for non JSON log formats
updated

2021-09-03 05:35 UTC, TehreemNisa commented on content/sre/logging/logging.md
> +Parsing application logs which are not in `JSON format` can be done using the below scenario.
updated

2021-09-03 05:35 UTC, TehreemNisa commented on content/sre/logging/logging.md
> +If the customer wants to parse logs themselves for example application log alerting like shown below
updated

2021-09-03 06:09 UTC, usamaahmadkhan approved these changes

2021-09-03 06:09 UTC, merged

2021-09-03 06:14 UTC, stakater-user commented
@usamaahmadkhan Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.155`