[WIP] Update Tenant Operator Documentation
stakater-archive/StakaterCloudDocs-Archived pull request #225
Opened 2021-11-11 05:56 UTC by abdulhaseeb2

2021-11-11 06:01 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-c15538f6`

2021-11-11 12:49 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-6f954695`

2021-11-11 13:03 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-593c24ca`

2021-11-12 12:27 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-c164c69f`

2021-11-12 16:55 UTC, rasheedamir commented on .vuepress/config.js
> +        title: "Multi-tenancy",
@abdulhaseeb2 we should call this tenant-operator specifically as it's our product

2021-11-13 07:52 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-70dedb79`

2021-11-13 10:22 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-0272de93`

2021-11-13 10:25 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-880aa3c8`

2021-11-15 08:57 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-9e38577c`

2021-11-15 10:31 UTC, rasheedamir approved these changes

2021-11-15 10:31 UTC, rasheedamir commented on content/sre/tenant-operator/overview.md
> +The idea of Tenant Operator is to use namespaces as independent sandboxes, where tenant applications can run independently from each other. To minimize cluster admin efforts, cluster admins shall con
Stakater App Agility Platform

2021-11-15 10:31 UTC, rasheedamir commented on content/sre/tenant-operator/overview.md
@abdulhaseeb2 we should clarify CRUDS; and instead list items

2021-11-15 10:31 UTC, rasheedamir commented on content/sre/tenant-operator/overview.md
> +## Roles
@abdulhaseeb2 roles? seems to be misplaced; or maybe the heading is wrong

2021-11-15 10:31 UTC, rasheedamir commented on content/sre/tenant-operator/overview.md
>  **Why?**
@abdulhaseeb2 should we really have the **Why** section?

2021-11-15 10:31 UTC, rasheedamir commented on content/sre/tenant-operator/overview.md
>  **Why?**
it seems to have a redundant information

2021-11-15 11:04 UTC, rasheedamir requested changes
check my comments

2021-11-16 08:53 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-225-de30f26d`

2021-11-16 10:48 UTC, rasheedamir approved these changes

2021-11-16 11:59 UTC, merged

2021-11-16 12:03 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.165`