Add vault csi documentation
stakater-archive/StakaterCloudDocs-Archived pull request #235
Opened 2021-12-13 14:56 UTC by hanzala1234

2021-12-13 15:00 UTC, stakater-user commented
@hanzala1234 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-6360620e`

2021-12-13 15:10 UTC, rasheedamir requested changes
Plz look at comments

2021-12-13 15:10 UTC, rasheedamir commented on content/sre/secrets/vault-csi.md
> +# Vault CSI Provider
@hanzala1234 @sabkat this document is hard to follow; are we suggesting multiple ways one can use it?

also can we place make it more like step by step guide?

can we add a supporting diagram which explains the whole workflow?

can we add auto restart as well?

2021-12-16 08:10 UTC, hanzala1234 commented on content/sre/secrets/vault-csi.md
> +# Vault CSI Provider
"this document is hard to follow; are we suggesting multiple ways one can use it"

we are not suggest multiple way. we are covering different use cases

2021-12-16 11:54 UTC, stakater-user commented
@hanzala1234 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-1cf7de23`

2021-12-18 21:32 UTC, rasheedamir commented on content/sre/secrets/vault-csi.md
> +# Vault CSI Provider
what ever is the workflow it should be super easy for developers to follow

2021-12-24 14:44 UTC, stakater-user commented
@hanzala1234 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-0227577a`

2021-12-24 14:59 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-e6dc32c0`

2021-12-24 15:02 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-531d6e10`

2021-12-24 15:02 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-f59832ef`

2021-12-24 15:04 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-5a516ad0`

2021-12-24 15:06 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-30100376`

2021-12-24 15:08 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-077e12ff`

2021-12-24 15:09 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-54353a08`

2021-12-24 15:30 UTC, stakater-user commented
@hanzala1234 Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-dbb3fb23`

2021-12-24 16:03 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-2ad543c5`

2021-12-24 16:06 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-d62e9a90`

2021-12-24 18:18 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-511bbb95`

2021-12-24 18:21 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-1f2f3856`

2021-12-24 18:22 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-bae2b038`

2021-12-24 18:25 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-235-00257c64`

2021-12-24 20:17 UTC, rasheedamir approved these changes

2021-12-24 20:17 UTC, merged

2021-12-24 20:21 UTC, stakater-user commented
@rasheedamir Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.173`