Update tenant-operator's integration config docs
stakater-archive/StakaterCloudDocs-Archived pull request #253
Opened 2022-02-02 12:46 UTC by LilShah

Related changes in TO: https://github.com/stakater-ab/tenant-operator/pull/190

2022-02-02 12:51 UTC, stakater-user commented
@LilShah Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-253-0017da9b`

2022-02-03 03:37 UTC, abdulhaseeb2 requested changes
Please don't use the integrationConfig of binero-test in the documentation.

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +      clientName: nexus3
Please remove this. As this feature isn't implemented yet, so no need to mention it here.

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +      - stakater-team
please remove this.

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +      - saap-cluster-admins
rename this to cluster-admins

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +      - ^hive-*
remove these

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +      - ^system:serviceaccount:hive-*
remove these

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +      url: https://iam-keycloak-openshift-stakater-auth.apps.binero-test.8sdzwd1l.kubeapp.cloud/
why are you using our actual URL in documentation?

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +      url: "https://stakater-vault-stakater-vault.apps.binero-test.8sdzwd1l.kubeapp.cloud/"
why are you using our actual URL in documentation?

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> -        stakater.com/kind: sandbox
Why have you removed sandbox? Please add it back

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +            - saap-cluster-admins
Again why are you using group names that stakater team manages? We don't want to show them on documentation, it should be abstract. Use `cluster-admins`

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +            - system:serviceaccount:openshift-stakater-argocd:argocd-argocd-application-controller
rename this to `system:serviceaccount:openshift-argocd:argocd-application-controller`

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +        namespace: stakater-auth
rename this to `openshift-auth`

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +        namespace: stakater-vault
rename this to `vault`

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +      accessorID: "auth_oidc_058b5e09"
rename the ID to a dummy ID like `auth_oidc_aa6aa9aa`

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +    - stakater-team
remove these and use dummy values. Like `cluster-admins`

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +    - ^hive-*
Remove these

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +    - ^system:serviceaccount:hive-*
Remove these

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +          - system:serviceaccount:openshift-stakater-argocd:argocd-argocd-application-controller
Use these instead

- system:serviceaccount:openshift-argocd:argocd-application-controller
- adam@stakater.com

2022-02-03 03:37 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +          - saap-cluster-admins
Use this instead
- cluster-admins

2022-02-03 05:47 UTC, stakater-user commented
@LilShah Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-253-aec7db5d`

2022-02-03 08:29 UTC, abdulhaseeb2 approved these changes
LGTM

2022-02-03 13:14 UTC, merged

2022-02-03 13:19 UTC, stakater-user commented
@LilShah Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.188`