[Tenant Operator] Add Network Policy use-case
stakater-archive/StakaterCloudDocs-Archived pull request #260
Opened 2022-02-18 12:59 UTC by abdulhaseeb2

2022-02-18 13:00 UTC, stakater-user commented
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/25dbc76edc06c037c7ae09818c4a6c2de144f721/checks) has Failed!

2022-02-18 13:21 UTC, tanalam2411 requested changes
Suggested few changes.

2022-02-18 13:21 UTC, tanalam2411 commented on content/sre/tenant-operator/usecases/configuring-multitenant-network-isolation.md
> +        tenant/network-restriction: "true"
Can we create a label based on the Template name, that would be an easy pattern to follow?
Create a template and to enable it just add a label by template name and set it to `true`

 `tenant/network-restriction: "true"` -> `tenant-network-policy: "true"`

2022-02-18 13:21 UTC, tanalam2411 commented on content/sre/tenant-operator/usecases/configuring-multitenant-network-isolation.md
> +  name: tenant-network-isolation-policy
Can we name `tenant-network-isolation-policy` -> `tenant-network-policy-group`, the name doesn't sound interesting but the pattern is easy to remember.

2022-02-21 05:59 UTC, stakater-user commented
@abdulhaseeb2 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/3a63ba796c812a7853c9fe7d1ab63a564661776a/checks) has Failed!

2022-02-21 09:03 UTC, stakater-user commented
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/25dbc76edc06c037c7ae09818c4a6c2de144f721/checks) has Failed!

2022-02-21 09:05 UTC, stakater-user commented
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/3a63ba796c812a7853c9fe7d1ab63a564661776a/checks) has Failed!

2022-02-21 09:13 UTC, stakater-user commented
@hanzala1234 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-260-3a63ba79`

2022-02-21 09:33 UTC, tanalam2411 approved these changes
LGTM

2022-02-21 09:34 UTC, merged

2022-02-21 09:38 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.195`