Admin privilege in keycloak to user for nexus doc added
stakater-archive/StakaterCloudDocs-Archived pull request #266
Opened 2022-02-25 07:55 UTC by TehreemNisa

2022-02-25 08:00 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-266-12b739e1`

2022-02-25 08:10 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-266-129db777`

2022-02-25 08:11 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-266-6388fb1a`

2022-02-25 09:45 UTC, usamaahmadkhan requested changes
1. Crop the URL/bookmarks bar of keycloak-1.png since it has the nonprod URL.
2. You need to add a reference of this page in .vuepress/config.js
3. Also provide a link to jump on this page from this page apropriately: https://docs.cloud.stakater.com/content/sre/repository/03-permissions.html

2022-02-25 11:16 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-266-f45d3032`

2022-02-25 14:38 UTC, usamaahmadkhan requested changes

2022-02-25 14:38 UTC, usamaahmadkhan commented on .vuepress/config.js
> +          "/content/sre/repository/08-grant-nexus-admin-keycloak.md"
This should come affter `03-permissions.md`

2022-02-25 14:46 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-266-4b1c87b7`

2022-02-26 09:06 UTC, usamaahmadkhan requested changes

2022-02-26 09:06 UTC, usamaahmadkhan commented on content/sre/repository/03-permissions.md
> +On first login you automatically get `nexus-oauth-viewer`. See [Admin privilege to user for nexus on Keycloack](../repository/08-grant-nexus-admin-keycloak.md) on how to configure admin role with key
See [ Granting Admin privilege to user for nexus on Keycloak] (../repository/08-grant-nexus-admin-keycloak.md) on how to configure admin role with keycloak for nexus.

2022-02-26 09:06 UTC, usamaahmadkhan commented on content/sre/repository/08-grant-nexus-admin-keycloak.md
> +## Admin privilege to user for nexus on Keycloack
Granting Admin privilege to user for nexus on Keycloak

2022-03-01 06:28 UTC, TehreemNisa commented on content/sre/repository/03-permissions.md
> +On first login you automatically get `nexus-oauth-viewer`. See [Admin privilege to user for nexus on Keycloack](../repository/08-grant-nexus-admin-keycloak.md) on how to configure admin role with key
added

2022-03-01 06:28 UTC, TehreemNisa commented on content/sre/repository/08-grant-nexus-admin-keycloak.md
> +## Admin privilege to user for nexus on Keycloack
added

2022-03-01 06:29 UTC, usamaahmadkhan approved these changes

2022-03-01 06:35 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:SNAPSHOT-PR-266-dd5f6706`

2022-03-01 06:36 UTC, merged

2022-03-01 06:40 UTC, stakater-user commented
@usamaahmadkhan Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/StakaterCloudDocs:v0.0.203`