[ Tenant-Operator ] Update tenant spec
stakater-archive/StakaterCloudDocs-Archived pull request #314
Opened 2022-06-17 12:33 UTC by hussnain612

Updated feature in tenant spec

2022-06-17 12:37 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-314-8dbd2df2`

2022-06-22 10:22 UTC, abdulhaseeb2 requested changes

2022-06-22 10:22 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/customresources.md
> +          stakater.com/current-tenant: alpha
please remove this annotation as it's not that meaningful. Secondly, this annotation is added by TO, so we don't need to mention it over here. Use some other meaningful annotation

2022-06-22 10:22 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/customresources.md
> +      app.kubernetes.io/managed-by: tenant-operator
Use a meaningful label that makes sense. As this will guide the user that what they can add.

2022-07-13 12:14 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-314-42c6a7e7`

2022-07-13 12:34 UTC, hussnain612 commented on content/sre/tenant-operator/customresources.md
> +          stakater.com/current-tenant: alpha
Updated

2022-07-13 12:34 UTC, hussnain612 commented on content/sre/tenant-operator/customresources.md
> +      app.kubernetes.io/managed-by: tenant-operator
Updated

2022-07-13 12:37 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-314-22b5ebf0`

2022-07-13 12:40 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-314-7323f23c`

2022-07-13 12:46 UTC, LilShah submitted a review, later dismissed

2022-07-15 04:40 UTC, stakater-user commented
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-314-808eed12`

2022-07-15 05:13 UTC, abdulhaseeb2 approved these changes

2022-07-15 05:13 UTC, merged

2022-07-15 05:18 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.253`