Update TO IntegrationConfig docs
stakater-archive/StakaterCloudDocs-Archived pull request #315
Opened 2022-06-17 13:39 UTC by MahnoorAsghar

Update TO IntegrationConfig docs - regex pattern in privilegedNamespaces and privilegedServiceAccounts

2022-06-17 13:42 UTC, stakater-user commented
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-315-eba748f7`

2022-06-20 05:29 UTC, abdulhaseeb2 requested changes

2022-06-20 05:29 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +`privilegedNamespaces:` Contains the list of `namespaces` ignored by the tenant-operator. The tenant-operator will not manage the `namespaces` in this list. Values in this list are regex patterns. Fo
and to ignore all `namespaces` starting with `openshift-` prefix

2022-06-20 05:29 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/integration-config.md
> +`privilegedServiceAccounts:` Contains the list of `ServiceAccounts` ignored by the tenant-operator. The tenant-operator will not manage the `ServiceAccounts` in this list. Values in this list are reg
to ignore all `ServiceAccounts` starting with `system:serviceaccount:openshift-` prefix

2022-06-20 08:05 UTC, stakater-user commented
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-315-1bf875d7`

2022-06-21 14:52 UTC, MahnoorAsghar commented on content/sre/tenant-operator/integration-config.md
> +`privilegedNamespaces:` Contains the list of `namespaces` ignored by the tenant-operator. The tenant-operator will not manage the `namespaces` in this list. Values in this list are regex patterns. Fo
@abdulhaseeb2 Please check

2022-06-21 14:53 UTC, MahnoorAsghar commented on content/sre/tenant-operator/integration-config.md
> +`privilegedServiceAccounts:` Contains the list of `ServiceAccounts` ignored by the tenant-operator. The tenant-operator will not manage the `ServiceAccounts` in this list. Values in this list are reg
@abdulhaseeb2 please check

2022-06-22 10:17 UTC, abdulhaseeb2 submitted a review, later dismissed

2022-06-22 12:12 UTC, stakater-user commented
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-315-97404938`

2022-06-22 14:57 UTC, stakater-user commented
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-315-80e34c96`

2022-06-24 06:06 UTC, tanalam2411 approved these changes

2022-06-24 06:07 UTC, merged

2022-06-24 06:11 UTC, stakater-user commented
@tanalam2411 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.247`