adding rhacs to cloud docs
stakater-archive/StakaterCloudDocs-Archived pull request #316
Opened 2022-06-22 09:16 UTC by TehreemNisa

2022-06-22 09:20 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-316-6242ee6a`

2022-06-22 09:21 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-316-f4257968`

2022-06-22 09:56 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-316-47ae8bf2`

2022-06-23 10:22 UTC, usamaahmadkhan requested changes

2022-06-23 10:22 UTC, usamaahmadkhan commented on content/sre/security/rhacs/02-permissions.md
> +1. human users and
First letter should always be Capital

2022-06-23 10:27 UTC, TehreemNisa commented on content/sre/security/rhacs/02-permissions.md
> +1. human users and
updated

2022-06-23 10:30 UTC, usamaahmadkhan approved these changes

2022-06-23 10:30 UTC, merged

2022-06-23 10:32 UTC, stakater-user commented
@TehreemNisa Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-316-4e645b7f`

2022-06-23 10:35 UTC, stakater-user commented
@usamaahmadkhan Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.246`