TO - Add troubleshooting question about vault permissions
stakater-archive/StakaterCloudDocs-Archived pull request #318
Opened 2022-06-23 13:52 UTC by MahnoorAsghar

If user is added to tenant, vault isn't updated with users permissions.
Jira ticket [reference](https://stakater-cloud.atlassian.net/browse/SA-982)

2022-06-23 13:56 UTC, stakater-user commented
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-318-845498fd`

2022-06-25 13:37 UTC, rasheedamir commented
@MahnoorAsghar the description of the problem isn't clear at all

2022-06-28 08:42 UTC, MahnoorAsghar commented
> 
description of the problem edited

2022-06-28 08:42 UTC, MahnoorAsghar commented
@abdulhaseeb2  please review

2022-06-28 09:21 UTC, abdulhaseeb2 requested changes

2022-06-28 09:21 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/troubleshooting.md
> +3. Vault denies that the user exists, and signs the user up via RHSSO. User is now created on RHSSO (You may check for the user on RHSSO). Tenant Operator logs say that the user does not exist on RHS
`Tenant Operator logs say that the user does not exist on RHSSO (but the user actually exists).` this is the log generated when the user did not exist in RHSSO.

2022-06-28 09:21 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/troubleshooting.md
> +3. Vault denies that the user exists, and signs the user up via RHSSO. User is now created on RHSSO (You may check for the user on RHSSO). Tenant Operator logs say that the user does not exist on RHS
So this can be added as a second point after `1. Add a new user to Tenant CR
`

2022-06-28 09:21 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/troubleshooting.md
> +If the TO controller pod is restarted at this point, TO will not show any error for the user after being restarted. Log in to Vault will also succeed after restart.
this should be removed from here and mentioned in the recommendations

2022-06-28 09:21 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/troubleshooting.md
> +It the user needs to be added immediately and it is not feasible to wait for next TO reconciliation, then add a label or annotation to the user, to force immediate reconciliation.
you can also add that you can restart TOs pods for instant reflection of permissions

2022-06-28 09:21 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/troubleshooting.md
> +It the user needs to be added immediately and it is not feasible to wait for next TO reconciliation, then add a label or annotation to the user, to force immediate reconciliation.
*`If the user`

2022-06-28 09:21 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/troubleshooting.md
> +### User permissions not updated immediately after user added to Tenant CR
this title is still not clear enough

2022-06-29 09:10 UTC, MahnoorAsghar commented on content/sre/tenant-operator/troubleshooting.md
> +3. Vault denies that the user exists, and signs the user up via RHSSO. User is now created on RHSSO (You may check for the user on RHSSO). Tenant Operator logs say that the user does not exist on RHS
Done

2022-06-29 11:15 UTC, MahnoorAsghar commented on content/sre/tenant-operator/troubleshooting.md
> +### User permissions not updated immediately after user added to Tenant CR
resolved

2022-06-29 11:19 UTC, stakater-user commented
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-318-4bc77d4b`

2022-06-29 11:42 UTC, abdulhaseeb2 requested changes

2022-06-29 11:42 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/troubleshooting.md
> +If a user is added to tenant resource, and the user does not exist in RHSSO, then Vault is not updated with user's permissions immediately.
then RHSSO is not updated with the user's Vault permission.

2022-06-29 11:42 UTC, abdulhaseeb2 commented on content/sre/tenant-operator/troubleshooting.md
> +### Vault user permissions not updated immediately if the user is added to Tenant CR, and the user does not exist in RHSSO
Vault user permissions are not updated if the user is added to a Tenant, and the user does not exist in RHSSO

2022-06-29 11:54 UTC, stakater-user commented
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-318-5d6c6d00`

2022-06-29 12:02 UTC, stakater-user commented
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-318-9982d22b`

2022-06-29 12:29 UTC, abdulhaseeb2 approved these changes
LGTM

2022-06-29 12:29 UTC, merged

2022-06-29 12:34 UTC, stakater-user commented
@abdulhaseeb2 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.248`